spring.application.name=TextQuest API

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/textquest
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway settings (disabled for now)
spring.flyway.enabled=false
